AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SpaceInsideHashLiteralBraces:
  Enabled: false
